run:
  name: infeas_netlib_infeasible_qpo3_nopresolve_1e-8_inf4
  output_dir: results
  parallelism: 1
  resume: true
  timeout_seconds: 360.0
  datasets:
  - name: netlib
    id: netlib_infeasible
    dataset_options:
      subset: infeasible
solvers:
- id: qpo3_nopresolve_1e-8
  solver: qpo3
  settings:
    tol_feas: 1.0e-08
    tol_gap_abs: 1.0e-08
    tol_gap_rel: 1.0e-08
    tol_infeas_abs: 0.0001
    tol_infeas_rel: 0.0001
    max_iters: 200
    time_limit: 300.0
    verbose: false
    presolve: false
