run:
  name: lp_kennington_osqp_1e-6
  output_dir: results
  parallelism: 1
  resume: true
  timeout_seconds: 360.0
  datasets:
  - name: kennington
    id: kennington
solvers:
- id: osqp_1e-6
  solver: osqp
  settings:
    eps_abs: 1.0e-06
    eps_rel: 1.0e-06
    max_iter: 1000000
    time_limit: 300.0
