run:
  name: lp_mittelmann_cuopt_1e-4
  output_dir: results
  parallelism: 1
  resume: true
  timeout_seconds: 360.0
  datasets:
  - name: mittelmann
    id: mittelmann
solvers:
- id: cuopt_1e-4
  solver: cuopt
  settings:
    eps: 0.0001
    time_limit: 300.0
