run:
  name: qp_qplib_proxqp_1e-4
  output_dir: results
  parallelism: 1
  resume: true
  timeout_seconds: 360.0
  datasets:
  - name: qplib
    id: qplib
    dataset_options:
      subset: all
solvers:
- id: proxqp_1e-4
  solver: proxqp
  settings:
    eps_abs: 0.0001
    eps_rel: 0.0001
    max_iter: 1000000
    time_limit: 300.0
