run:
  name: lpbig_mittelmann0_highs_1e-4
  output_dir: results
  parallelism: 1
  resume: true
  timeout_seconds: 1860.0
  datasets:
  - name: mittelmann
    id: mittelmann0
    include:
    - Dual2_5000
    - a2864
    - bdry2
    - chromaticindex1024-7
    - ex10
    - fhnw-binschedule1
    - graph40-40
    - neos-3025225
    - neos-5251015
    - qap15
    - scpm1
    - supportcase19
    - thk_48
solvers:
- id: highs_1e-4
  solver: highs
  settings:
    primal_feasibility_tolerance: 0.0001
    dual_feasibility_tolerance: 0.0001
    time_limit: 1800.0
