run:
  name: infeas_netlib_infeasible_scs_cpu_1e-8_inf4
  output_dir: results
  parallelism: 1
  resume: true
  timeout_seconds: 360.0
  datasets:
  - name: netlib
    id: netlib_infeasible
    dataset_options:
      subset: infeasible
solvers:
- id: scs_cpu_1e-8
  solver: scs
  settings:
    eps_abs: 1.0e-08
    eps_rel: 1.0e-08
    max_iters: 1000000
    time_limit_secs: 300.0
    eps_infeas: 0.0001
