run:
  name: sdp_sdplib_clarabel_1e-8_try_qpG51
  output_dir: results
  parallelism: 1
  resume: true
  timeout_seconds: 960.0
  datasets:
  - name: sdplib
    id: sdplib
    include:
    - qpG51
solvers:
- id: clarabel_1e-8
  solver: clarabel
  settings:
    tol_feas: 1.0e-08
    tol_gap_abs: 1.0e-08
    tol_gap_rel: 1.0e-08
    time_limit: 900.0
