run:
  name: lp_kennington_qtqp_cudss_1e-6
  output_dir: results
  parallelism: 1
  resume: true
  timeout_seconds: 360.0
  datasets:
  - name: kennington
    id: kennington
solvers:
- id: qtqp_cudss_1e-6
  solver: qtqp
  settings:
    tol_feas: 1.0e-06
    tol_gap_abs: 1.0e-06
    tol_gap_rel: 1.0e-06
    max_iter: 200
    verbose: false
    linear_solver: cudss
