run:
  name: lp_miplib_relax_qtqp_mkl_1e-4
  output_dir: results
  parallelism: 1
  resume: true
  timeout_seconds: 360.0
  datasets:
  - name: miplib
    id: miplib_relax
    exclude:
    - n9-3
    - neos-3754224-navua
    - neos-5075914-elvire
    - rococoC11-011100
    - toll-like
    - mad_BAK
solvers:
- id: qtqp_mkl_1e-4
  solver: qtqp
  settings:
    tol_feas: 0.0001
    tol_gap_abs: 0.0001
    tol_gap_rel: 0.0001
    max_iter: 200
    verbose: false
    linear_solver: pardiso
