run:
  name: sdp_sdplib_scs_cudss_1e-4_thetaG51
  output_dir: results
  parallelism: 1
  resume: true
  timeout_seconds: 960.0
  datasets:
  - name: sdplib
    id: sdplib
    include:
    - thetaG51
solvers:
- id: scs_cudss_1e-4
  solver: scs
  settings:
    eps_abs: 0.0001
    eps_rel: 0.0001
    max_iters: 1000000
    time_limit_secs: 900.0
    linear_solver: cudss
