run:
  name: sdp_mittelmann_sdp_scs_cpu_1e-4
  output_dir: results
  parallelism: 1
  resume: true
  timeout_seconds: 960.0
  datasets:
  - name: mittelmann_sdp
    id: mittelmann_sdp
    dataset_options:
      subset: all
solvers:
- id: scs_cpu_1e-4
  solver: scs
  settings:
    eps_abs: 0.0001
    eps_rel: 0.0001
    max_iters: 1000000
    time_limit_secs: 900.0
