run:
  name: qp_qplib_qtqp_cudss_1e-8
  output_dir: results
  parallelism: 1
  resume: true
  timeout_seconds: 360.0
  datasets:
  - name: qplib
    id: qplib
    dataset_options:
      subset: all
solvers:
- id: qtqp_cudss_1e-8
  solver: qtqp
  settings:
    tol_feas: 1.0e-08
    tol_gap_abs: 1.0e-08
    tol_gap_rel: 1.0e-08
    max_iter: 200
    verbose: false
    linear_solver: cudss
