run:
  name: lp_miplib_relax_scs_cudss_1e-6_miss4
  output_dir: results
  parallelism: 1
  resume: true
  timeout_seconds: 360.0
  datasets:
  - name: miplib
    id: miplib_relax
    include:
    - mad
    - neos-2987310-joes
    - piperout-27
    - rococoC10-001000
solvers:
- id: scs_cudss_1e-6
  solver: scs
  settings:
    eps_abs: 1.0e-06
    eps_rel: 1.0e-06
    max_iters: 1000000
    time_limit_secs: 300.0
    linear_solver: cudss
