run:
  name: lp_miplib_relax_piqp_1e-4_big6
  output_dir: results
  parallelism: 1
  resume: true
  timeout_seconds: 360.0
  datasets:
  - name: miplib
    id: miplib_relax
    include:
    - square47
    - square41
    - neos-3402454-bohle
    - neos-2075418-temuka
    - supportcase19
    - neos-5114902-kasavu
solvers:
- id: piqp_1e-4
  solver: piqp
  settings:
    eps_abs: 0.0001
    eps_rel: 0.0001
    max_iter: 1000000
    time_limit: 300.0
