run:
  name: infeas_netlib_infeasible_clarabel_1e-6_inf
  output_dir: results
  parallelism: 1
  resume: true
  timeout_seconds: 360.0
  datasets:
  - name: netlib
    id: netlib_infeasible
    dataset_options:
      subset: infeasible
solvers:
- id: clarabel_1e-6
  solver: clarabel
  settings:
    tol_feas: 1.0e-06
    tol_gap_abs: 1.0e-06
    tol_gap_rel: 1.0e-06
    time_limit: 300.0
    tol_infeas_abs: 1.0e-06
    tol_infeas_rel: 1.0e-06
