run:
  name: infeas_netlib_infeasible_highs_1e-6
  output_dir: results
  parallelism: 1
  resume: true
  timeout_seconds: 360.0
  datasets:
  - name: netlib
    id: netlib_infeasible
    dataset_options:
      subset: infeasible
solvers:
- id: highs_1e-6
  solver: highs
  settings:
    primal_feasibility_tolerance: 1.0e-06
    dual_feasibility_tolerance: 1.0e-06
    time_limit: 300.0
