run:
  name: infeas_sdplib_infeasible_cvxopt_1e-6
  output_dir: results
  parallelism: 1
  resume: true
  timeout_seconds: 960.0
  datasets:
  - name: sdplib
    id: sdplib_infeasible
    include:
    - infd1
    - infd2
    - infp1
    - infp2
solvers:
- id: cvxopt_1e-6
  solver: cvxopt
  settings:
    abstol: 1.0e-06
    reltol: 1.0e-06
    feastol: 1.0e-06
