run:
  name: lp_kennington_cuopt_1e-5
  output_dir: results
  parallelism: 1
  resume: true
  timeout_seconds: 360.0
  datasets:
  - name: kennington
    id: kennington
solvers:
- id: cuopt_1e-5
  solver: cuopt
  settings:
    eps: 1.0e-05
    time_limit: 300.0
