run:
  name: lpbig_mittelmann1_scs_cudss_1e-5
  output_dir: results
  parallelism: 1
  resume: true
  timeout_seconds: 1860.0
  datasets:
  - name: mittelmann
    id: mittelmann1
    include:
    - Primal2_1000
    - bharat
    - datt256_lp
    - dlr1
    - dlr2
    - irish-electricity
    - neos-5052403-cygnet
    - physiciansched3-3
    - s100
    - supportcase10
    - thk_63
    - tpl-tub-ws1617
solvers:
- id: scs_cudss_1e-5
  solver: scs
  settings:
    eps_abs: 1.0e-05
    eps_rel: 1.0e-05
    max_iters: 1000000
    time_limit_secs: 1800.0
    linear_solver: cudss
