run:
  name: lpbig_mittelmann0_scs_cudss_1e-5
  output_dir: results
  parallelism: 1
  resume: true
  timeout_seconds: 1860.0
  datasets:
  - name: mittelmann
    id: mittelmann0
    include:
    - Dual2_5000
    - a2864
    - bdry2
    - chromaticindex1024-7
    - ex10
    - fhnw-binschedule1
    - graph40-40
    - neos-3025225
    - neos-5251015
    - qap15
    - scpm1
    - supportcase19
    - thk_48
solvers:
- id: scs_cudss_1e-5
  solver: scs
  settings:
    eps_abs: 1.0e-05
    eps_rel: 1.0e-05
    max_iters: 1000000
    time_limit_secs: 1800.0
    linear_solver: cudss
