run:
  name: qp_maros_meszaros_scs_cudss_1e-5
  output_dir: results
  parallelism: 1
  resume: true
  timeout_seconds: 360.0
  datasets:
  - name: maros_meszaros
    id: maros_meszaros
solvers:
- id: scs_cudss_1e-5
  solver: scs
  settings:
    eps_abs: 1.0e-05
    eps_rel: 1.0e-05
    max_iters: 1000000
    time_limit_secs: 300.0
    linear_solver: cudss
