run:
  name: lp_miplib_relax_qpo3_1e-8
  output_dir: results
  parallelism: 1
  resume: true
  timeout_seconds: 360.0
  datasets:
  - name: miplib
    id: miplib_relax
    dataset_options:
      max_size_mb: 20
solvers:
- id: qpo3_1e-8
  solver: qpo3
  settings:
    tol_feas: 1.0e-08
    tol_gap_abs: 1.0e-08
    tol_gap_rel: 1.0e-08
    max_iters: 200
    time_limit: 300.0
    verbose: false
