run:
  name: lpbig_mittelmann1_qpo3_1e-8
  output_dir: results
  parallelism: 1
  resume: true
  timeout_seconds: 1860.0
  datasets:
  - name: mittelmann
    id: mittelmann1
    include:
    - Primal2_1000
    - bharat
    - datt256_lp
    - dlr1
    - dlr2
    - irish-electricity
    - neos-5052403-cygnet
    - physiciansched3-3
    - s100
    - supportcase10
    - thk_63
    - tpl-tub-ws1617
solvers:
- id: qpo3_1e-8
  solver: qpo3
  settings:
    tol_feas: 1.0e-08
    tol_gap_abs: 1.0e-08
    tol_gap_rel: 1.0e-08
    max_iters: 200
    time_limit: 1800.0
    verbose: false
